apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: chiragrajput/ecom-api:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: api-configmap
              key: db_host
        - name: DB_USER
          valueFrom: 
            configMapKeyRef:
              name: api-configmap
              key: db_user
        - name: DB_NAME
          valueFrom: 
            configMapKeyRef:
              name: api-configmap
              key: db_name           

---
# for catering to requests from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: api-external-service
spec:
  selector:
    app: api # selector to which this service caters
  type: LoadBalancer # indicates an external service -> assigned an external IP addr
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080                
      nodePort: 30000 # for browser -> range: [30000,32767]